### PR TITLE
Add new FMU to revisions

### PR DESCRIPTION
**Pull request by AlexandrShipovsky**
Hello!
I'm from the ClearSky company. We are starting to develop an autopilot according to the Pixhawk v6X standard and I would like to reserve a revision number

### CODE REVIEW

**Comment by mrpollo** [comment]
hey @davids5 can you please review

**Review by davids5 — APPROVED** [review]
OK looks good.  @mrpollo Please merge

**Comment by mrpollo** [comment]
Thanks for the PR @AlexandrShipovsky; please reach out if you need any assistance with your design.

**Comment by AlexandrShipovsky** [comment]
@mrpollo okay, thank you!

**Pull request merged**
