### PR TITLE
Update DS-019 Pixhawk versions and revisions.md

### PR DESCRIPTION
**Pull request by vincentpoont2**
Add Holybro FMUv6x rev8 sensor set. 

The current sensor set is getting outdated so we would like to add a new sensor set that replace the current Rev3/4.

### CODE REVIEW

**Comment by vincentpoont2** [comment]
@mrpollo @davids5 Can we proceed with this?

**Comment by mrpollo** [comment]
@davids5 can you confirm this is available and viable?

**Comment by davids5** [comment]
> @davids5 can you confirm this is available and viable?

It is. We have allocated quite a few for HB. We need to look at using the EEPROM for the Next HB sensor set.

**Comment by vincentpoont2** [comment]
> > @davids5 can you confirm this is available and viable?
> 
> It is. We have allocated quite a few for HB. We need to look at using the EEPROM for the Next HB sensor set.

What are the steps to use the EEPROM?

**Comment by vincentpoont2** [comment]
@davids5 Since there are still a few open allocation, can we proceed with the REV8 for this one? We have prototype hardware ready. 

At the moment, we are unable on the steps to use EEPROM. We can review the steps to use EEPROM and if we have another REV in the future, we can certainly use the EEPROM for that.

**Comment by davids5** [comment]
> > > @davids5 can you confirm this is available and viable?
> > 
> > 
> > It is. We have allocated quite a few for HB. We need to look at using the EEPROM for the Next HB sensor set.
> 
> What are the steps to use the EEPROM?

The HW resisters on the FMUM are set to Code point 7.   (R1 46.4K  and R2 84.5K
A code point is reserved from  above 0x10 (say 0x1009) it is marked | EEPROM |  Holy Bro Rev 9 Sensor Set  |
In production the IMU board's EEPROM is loaded with [the information](https://github.com/PX4/PX4-Autopilot/blob/071565a8ad2a8e4f480a042d72e5fcfbb699157e/platforms/nuttx/src/px4/common/include/px4_platform/board_hw_eeprom_rev_ver.h#L46C3-L50C15) here. Drone Code will provide you a tools to do this this.

**Comment by davids5** [comment]
> @davids5 Since there are still a few open allocation, can we proceed with the REV8 for this one? We have prototype hardware ready.

Yes

> 
> At the moment, we are unfamiliar with the steps to use EEPROM. We can review the steps to use EEPROM and if we have another REV in the future, we can certainly use the EEPROM for that.

**Comment by vincentpoont2** [comment]
@mrpollo Please merge

**Pull request merged**
